name: publish

on: workflow_dispatch

jobs:
  publish-mediawiki-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Mediawiki Docker image
      run: |
        docker build . --tag ghcr.io/${{ github.actor }}/mediawiki:latest
        docker run ghcr.io/${{ github.actor }}/mediawiki:latest
        docker push ghcr.io/${{ github.actor }}/mediawiki:latest
